### ISSUE TITLE
After the recyclerview in SlidingView is a child view, setScrollableViewHelper has no effect

### ISSUE THREAD

**Issue by ZXHHYJ** [hannesa2/AndroidSlidingUpPanel#94]
`mainSlidingView.setScrollableViewHelper(ScrollableViewHelper())`

**Comment by hannesa2** [comment]
Did you debuged into this https://github.com/hannesa2/AndroidSlidingUpPanel/blob/1ba722a33311c0aef432c950831c5bbfa1846362/library/src/main/java/com/sothree/slidinguppanel/SlidingUpPanelLayout.java#L992 after set your helper.

Btw, to set _exactly_ this helper makes currently no sense, because it sets it by default
https://github.com/hannesa2/AndroidSlidingUpPanel/blob/1ba722a33311c0aef432c950831c5bbfa1846362/library/src/main/java/com/sothree/slidinguppanel/SlidingUpPanelLayout.java#L163
